config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Devise + ActiveAdmin
  #devise_for :admins, ActiveAdmin::Devise.config
  #devise_for :users, ActiveAdmin::Devise.config
  #ActiveAdmin.routes(self)

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  ActiveAdmin.routes(self)

  # API
  # /api/v1/
  mount API::Base => '/'

  # API routes

  # GET
  # all publications                        => publications
  # single publication details              => publications/:id
  # all issues of a publication             => publications/:id/issues
  # all years of a publication              => publications/:id/years
  # all the publications in a year,
  # grouped by month                        => publication/:publication_id/year/:year

  # all issues                              => issues/
  # single issue details                    => issues/:id
  # year of issues of a publication         => issues/:publication_id/year/:year
  # unique months of a publication          => issues/unique_months
  # all the publications in a year/month    => issues/:publication_id/year/:year/:month
  # all the publications in a year          => publication/:publication_id/year/:year

  # POST
  # upload an issue                         => issues/

  # Application
  root "viewer#index"

  get "/search", to: "viewer#search"
  get "/search_results", to: "viewer#search_results"

  get "/corrector", to: "corrector#index"
  post "/corrector", to: "corrector#create"
  get "/corrector/score", to: "corrector#score"
  get "/corrector/help", to: "corrector#help"
  get "/user/profile", to: "corrector#profile"

  get "/publication/:publication_id", to: "viewer#index"
  get "/publication/:publication_id/issue/:issue_id", to: "viewer#index"
  get "/publication/:publication_id/issue/:issue_id/page/:page_id", to: "viewer#index"
  get "/issue/:issue_id", to: "viewer#index"
  get "/issue/:issue_id/page/:page_id", to: "viewer#index"
  get "/:issue_id", to: "viewer#index"
  get "/:issue_id/:page_id", to: "viewer#index"

end

app/controllers/viewer_controller.rb
class ViewerController < ApplicationController

  # Viewer Index
  def index

    # Get params from URL
    publication_id = params[:publication_id]
    issue_id = params[:issue_id]
    page_number = params[:page_id]

    get_url_information(publication_id, issue_id, page_number)


    respond_to do |format|
      format.html # viewer/index.html.erb
    end

  end



  # Search functionality, supplied via JS and partials
  def search
    @publications = Publication.all.select(:id, :name)

    # Get the Publication ID
    publication_id = params[:publication_id] || Publication.first.id

    # Get oldest and news dates of issues belong to a publication
    if Rails.env.development? # only in development for now
      issue_dates = Issue.date_edges(publication_id) # All issues
    else
      issue_dates = Issue.of_scans_type.date_edges(publication_id) # Only issues of scan type for now
    end

    # Fill the dates from the params and not from the DB,
    # if it's a search reload
    @oldest_issue_date = issue_dates[0].to_time.strftime('%d/%m/%Y')
    @newest_issue_date = issue_dates[1].to_time.strftime('%d/%m/%Y')
    @from_date = params[:from_date] || @oldest_issue_date
    @to_date = params[:to_date] || @newest_issue_date

    respond_to do |format|
      #format.html # viewer/search.html.erb
      format.js # viewer/search.js.erb
    end

  end


  # Gets the search results and paginates them
  def search_results

    publication_id = params[:publication_id] || Publication.first.id
    pagination_page = params[:page] || 0
    from_date = Date.parse(params[:from_date], '%d/%m/%Y')
    to_date = Date.parse(params[:to_date], '%d/%m/%Y')
    sort_attribute = params[:sort_attribute] || '_score'
    sort_direction = params[:sort_direction] || 'desc'

    @results = Page.search_by_date_interval(params[:term], publication_id, pagination_page, from_date, to_date, sort_attribute, sort_direction )


    respond_to do |format|
      format.js # viewer/search_results.js.erb
    end

  end

  private

  # Geth the current information and output to a inline JS object in the returned page
  def get_url_information(publication_id, issue_id, page_number)
  
    if publication_id
      publication = Publication.find(publication_id)
      publication_name = publication.name
      publication_frequency = publication.frequency
    end
    
    if issue_id
      issue = Issue.find(issue_id)
      year = issue.date.year
      month = "%.2d" % issue.date.month.to_i
      day = issue.date.day
      #pages_widths_and_heights = issue.pages_widths_and_heights
      number_of_pages = issue.pages.size # get it from the pages_widths array, no need for another DB call

      unless publication_id
        publication_id = issue.publication_id
        publication = Publication.find(publication_id)
        publication_name = publication.name
        publication_frequency = publication.frequency
      end

      if page_number
        if page_number.to_i > number_of_pages.to_i
          page_number = number_of_pages.to_i
        end
        
        page = Page.where(:issue_id => issue_id).where(:number => page_number).first
        page_id = page.id
        page_og_image_url = page.get_og_image_url
      else
        page_number = 1
        page = Page.where(:issue_id => issue_id).where(:number => page_number).first
        page_id = page.id
        page_og_image_url = page.get_og_image_url
      end
    end

    # Pass the information to inline JS in this page
    gon.push({
      :publication => {
        :id => publication_id,
        :name => publication_name,
        :frequency => publication_frequency
      },
      :issue => {
        :id => issue_id,
        :date => {
          :year => year,
          :month => month,
          :day => day
        },
        :number_of_pages => number_of_pages,
        #:pages_widths_and_heights => pages_widths_and_heights,
        :page => page_number,
        :page_id => page_id
      }
    })

    # The Viewer URL doesn't always have a issue and page params,
    # so that case to be taken care of.
    # OG params have also to be server-side rendered.
    # TODO: needs to adapt better if it is a daily publication
    if (issue_id && page_number)
      page_title = "#{publication_name} - #{month}/#{year} - #{t('viewer.page')} #{page_number.to_i}"
      page_og_url = "#{ENV['MARCHIVER_URL']}#{issue_id}/#{page_number}"
      page_og_description = page.text_content ? page.text_content.slice(0,300) : ''
    elsif (issue_id)
      page_title = "#{publication_name} - #{month}/#{year}"
      page_og_url = "#{ENV['MARCHIVER_URL']}#{issue_id}"
      page_og_description = page.text_content ? page.text_content.slice(0,300) : ''
    else
      page_title = ''
      page_og_url = ''
      page_og_description = ''
      page_og_image_url = ''
    end

    set_meta_tags index: true,
                  follow: true,
                  title: page_title,
                  description: page_og_description.slice(0,160),
                  og: {
                    title:        page_title,
                    author:       publication_name,
                    description:  page_og_description,
                    type:         'article',
                    url:          page_og_url,
                    image: {
                      _: page_og_image_url,
                      width:      1200,
                      height:     630
                    }
                  },
                  twitter: {
                    card:         'summary_large_image',
                    url:          page_og_url,
                    title:        page_title,
                    description:  page_og_description,
                    image:        page_og_image_url
                  }

  end


end

app/helpers/viewer_helper.rb
module ViewerHelper
end

app/views/viewer/_navbar.html.erb
<!-- Fixed navbar -->
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">

    <!-- Title at the center -->
    <div class="navbar-header">
      <div class="navbar-brand">
          <h1><a href="/"><%= ENV['ARCHIVE_NAME'] %></a></h1>
      </div>
    </div>

    <!-- Mobile -->
    <div class="mobile_nav">
      <!-- Issue Nav -->
      <%= link_to '#', class: 'btn navbar-btn pull-left visible-xs issue-nav_toggle' do %>
        <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>
      <% end %>

      <%= link_to '/search', class: 'btn navbar-btn pull-right visible-xs search_toggle' , remote: true do %>
        <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
      <% end %>
    </div>


    <!-- Desktop -->
    <!-- Publication navigation -->
    <div class="mobile_nav_issue_nav"> <!-- class to enable nav overlay -->
      <ul class="nav navbar-nav navbar-left">
         <h4><%= t('viewer.select_issue') %></h4>
         <div class="navigation">
            
            <select class="publications ui dropdown">
            </select>
            <select class="years ui dropdown">
            </select>
            <select class="months ui dropdown">
            </select>
            <select class="days ui dropdown">
            </select>
        
        </div>
      </ul>
    </div>

    <!-- Search -->
    <ul class="nav navbar-nav navbar-right">
      <li class="search_toggle">
        <%= link_to '/search', remote: true do %>
          <span class="glyphicon glyphicon-search" aria-hidden="true"></span><%= t('viewer.search') %>
        <% end %>
      </li>
    </ul>

  </div>
</nav>

app/views/viewer/_search.html.erb
<script type="text/javascript">
  
  // Loading only here as it relates to search fields that
  // are not present on the initial Viewer load
  $(function() {

    // Trigger order options for results
    $(".search_results_info span#order_older, .search_results_info span#order_recent, .search_results_info span#order_score").on('click', function(){

        $(this).siblings('span').removeClass('active');
        $(this).addClass('active');


        attribute = $(this).data('sort-attribute')
        direction = $(this).data('sort-direction')

        sort(attribute, direction);

        $("#form_search" ).submit();

    });

    // Filter fields
    // add hidden input fields with ordering options
    function sort(attribute, direction) {

      // Clear form attributes
      $("#form_search input[name='sort_attribute']").remove();
      $("#form_search input[name='sort_direction']").remove();
       
      $('<input>').attr({
          type: 'hidden',
          name: 'sort_attribute',
          value: attribute
      }).prependTo('#form_search div.term_input');

      $('<input>').attr({
          type: 'hidden',
          name: 'sort_direction',
          value: direction
      }).prependTo('#form_search div.term_input');

    };


    // Format the date input fields
    $('#from_date, #to_date').toArray().forEach(function(input_field){
      new Cleave(input_field, {
        date: true,
        datePattern: ['d', 'm', 'Y']
        //datePattern: ['m','Y'] // For month and year
      });
    });

    // Reset the results on each search submission
    $("#form_search").submit(function( event ) {
      $('.search_results_list').empty();
    });

    // Submit from on click
    $("#search a.search_submit").on('click', function(event) {
      event.preventDefault();
      $(".search_results_info span#order_score").trigger( "click" );
      $(".search_results").removeClass('hide');
    })

    // Submit on any search field enter
    $('#search input[type=text]').keypress(function(e) {
      if(e.which == 13) {
        $("#search a.search_submit").trigger('click');
      }
    });


  });

</script>

 <div id="search" class="container-fluid">  
  
      <div class="search_form container-fluid">
        <div class="container">
        <div class="row">
          <div class="col-md-12">
          <%= form_for :term, url: search_results_path, method: :get, html: { id: "form_search"}, remote: true do |form| %>
              <div class="term_input">
                <%= text_field_tag :term, params[:term], class: 'term_input_field' %>
                <%= link_to t('viewer.search_action'), '', class: 'btn btn-sm search_submit' %>
              </div>
              <div class="date_inputs"> 
                <span class="from"><%= t('viewer.date_from') %></span> 
                <%= text_field_tag :from_date, @from_date, class: 'date_input_field' %>
                 <span class="to"><%= t('viewer.date_between') %></span> 
                <%= text_field_tag :to_date, @to_date, class: 'date_input_field' %>
              </div>
              <% if (@publications.size > 1) %>
                <%= select_tag :publication_id, options_from_collection_for_select(@publications, "id", "name")%>
              <% end %>            
          <% end %>
          </div>
        </div> <!-- /.row -->
        </div> <!-- /.container -->
      </div> <!-- /.search_form.container fluid -->


      <!-- Search Results -->
      <div class="search_results hide">
        
        <!-- Search Results info -->
        <div class="search_results_info_container container-fluid">
            <div class="container">
            <div class="search_results_info row">
              <p class="results_count">
              </p>
              <p class="order_results">
                <span class="order_by"><%= t('viewer.order_by') %></span> <span id="order_score"  class="order_action" data-sort-attribute="_score" data-sort-direction="desc"><%= t('viewer.order_relevancy') %></span> | <span id="order_older" class="order_action"  data-sort-attribute="date" data-sort-direction="asc"><%= t('viewer.order_older') %></span> | <span id="order_recent" class="order_action" data-sort-attribute="date" data-sort-direction="desc"><%= t('viewer.order_recent') %>
              </p>
            </div>
        </div>

      </div> <!-- /results -->

  </div> <!-- /search -->

app/views/viewer/_search_results_count.html.erb
<strong><%= number_with_delimiter(@results.total_count, delimiter: ".") %></strong> <%= t('viewer.result').pluralize(@results.total_count) %>

app/views/viewer/_search_results_item.html.erb
  <!-- X results -->
  <% @results.each do |result| %>

      <% result_link = "/#{result.issue.id}/#{result.number}?highlighted_strings=#{result.search_highlights[:text].html_safe.scan(/<em>(.*?)<\/em>/).map{|str| str[0].downcase}.uniq.join(',')}" %>
      <div class="result col-md-3 col-md-offset-0 col-sm-4 col-sm-offset-0 col-xs-12 col-xs-offset-0">
        <div class="page_thumbnail">
          <%= link_to image_tag(result.get_thumbnail_url), result_link %>
        </div>
        <h5><%= l(result.issue.date, format: "%Y, %B") %></h5>
        <p class="page_number"> <%= t('viewer.page') %> <%= result.number %></p>
        <p class="result_text">
          <%= result.search_highlights[:text].html_safe %>... <span class="read_more"><%= link_to(t('viewer.read_more'), result_link) %></span>
        </p>
      </div>

  <% end %>

app/views/viewer/_search_results_list.html.erb
    <!-- Search results list -->
    <% if @results.size != 0 %>
    <div class="search_results_list infinite_results container">
      <div class="row">

        <div class="results_append">
          <%= render :partial => 'search_results_item', :object => @results %>
        </div>

        <div class="search_pagination">
        </div>
      
      </div>
    </div>

    <% end %>

app/views/viewer/index.html.erb
<div id="viewer">


  <!-- Top Nav -->
  <%= render "navbar" %>

  <!-- Search -->
  <div id="search_container">
  </div>

  <!-- Issue Viewer -->
  <div id="map_container" class="container-fluid">
    <div id="map"></div>
  </div>

</div>

app/views/viewer/search.js.erb
// Check if search is already present
if ( $('#search_container #search').length ) {

  // If search is present remove it
  $('#search_container').empty();
  // Show map again
  $('#map_container').show();

} else {

  // Show search
  $("<%=j render(:partial => 'search') %>")
    .prependTo("#search_container")
    .show();
}

app/views/viewer/search_results.js.erb
// Append data

// On first load
<% if (@results.current_page == 1) %>

    // Update counter
    $('.search_results_info .results_count').html("<%=j render(:partial => 'search_results_count', :object => @results) %>")

    // Add results
    // But remove previous results first if they exist
    $(".search_results_list").remove(); 
    $(".search_results").append("<%=j render(:partial => 'search_results_list', :object => @results) %>")

    <% if @results.count != 0 %>
      $('#map_container').hide();
    <% end %>


    $(function(){

    // Infinite loading search results
    $('.search_results_list.infinite_results').infinitePages({
      //debug: true,
      buffer: 300,
      //context: '.search_results',
      navSelector: 'a[rel=next]',
      loading: function() {
        //return $(this).text("<%= t('viewer.loading_next_page') %>");
        //return $(this).html("<div class='loader'></div>");
      },
      error: function() {
        return $(this).button("<%= t('viewer.loading_next_page_error') %>");
      }
    });


  });

// Support for infinite pages
<% else %>
  // Infinite pages
  $(".search_results_list.infinite_results .results_append").append("<%=j render(:partial => 'search_results_item', :object => @results) %>")
<% end %>

// Update pagination link
<% if @results.last_page? %>
  $('.search_pagination').html(""); // Nothing else to load
<% else %>
  $('.search_pagination').html("<%=j link_to_next_page(@results, 'Next Page', :remote => true) %>");
  // Place the spinner, instead of words
  setTimeout(function(){
    $('.search_pagination a').html("<div class='loader'></div>") // Add Spinner
   }, 500); 
<% end %>