config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Devise + ActiveAdmin
  #devise_for :admins, ActiveAdmin::Devise.config
  #devise_for :users, ActiveAdmin::Devise.config
  #ActiveAdmin.routes(self)

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  ActiveAdmin.routes(self)

  # API
  # /api/v1/
  mount API::Base => '/'

  # API routes

  # GET
  # all publications                        => publications
  # single publication details              => publications/:id
  # all issues of a publication             => publications/:id/issues
  # all years of a publication              => publications/:id/years
  # all the publications in a year,
  # grouped by month                        => publication/:publication_id/year/:year

  # all issues                              => issues/
  # single issue details                    => issues/:id
  # year of issues of a publication         => issues/:publication_id/year/:year
  # unique months of a publication          => issues/unique_months
  # all the publications in a year/month    => issues/:publication_id/year/:year/:month
  # all the publications in a year          => publication/:publication_id/year/:year

  # POST
  # upload an issue                         => issues/

  # Application
  root "viewer#index"

  get "/search", to: "viewer#search"
  get "/search_results", to: "viewer#search_results"

  get "/corrector", to: "corrector#index"
  post "/corrector", to: "corrector#create"
  get "/corrector/score", to: "corrector#score"
  get "/corrector/help", to: "corrector#help"
  get "/user/profile", to: "corrector#profile"

  get "/publication/:publication_id", to: "viewer#index"
  get "/publication/:publication_id/issue/:issue_id", to: "viewer#index"
  get "/publication/:publication_id/issue/:issue_id/page/:page_id", to: "viewer#index"
  get "/issue/:issue_id", to: "viewer#index"
  get "/issue/:issue_id/page/:page_id", to: "viewer#index"
  get "/:issue_id", to: "viewer#index"
  get "/:issue_id/:page_id", to: "viewer#index"

end

app/controllers/corrector_controller.rb
class CorrectorController < ApplicationController
  # Specify a different parent layout
  layout "corrector"

  # Reset the app locale, as ActiveAdmin is always in English
  before_action :reset_app_locale

  # User needs to be authenticated
  before_action :authenticate_user!


  # Main page
  def index

    @user = User.find(current_user.id)

    publication_id = nil
    # Original
    #@issue = Issue.of_scans_type.order("RAND()").first
    #@page = Page.where(:issue_id => @issue.id, :number => 1).order("RAND()").first
    @page = Page.without_corrections.order("RAND()").first
    @issue = Issue.find(@page.issue)

    # Dev version
    # where you set the issue number and the page number,
    # to be the cover/first page with less lines
    #@issue = Issue.find(118)
    #@page = Page.where(:issue_id => @issue.id).where(:number => 1).first
    @issue_number_of_pages = @issue.number_of_pages

    random_page_content_id = PageContent.where(:page_id => @page.id).first.id
    # TODO
    #@mjson = Azure.to_mjson(random_page_content_id)
    @mjson = Page.find(@page.id).to_mjson


    current_page_information(publication_id, @issue.id, @page.number, random_page_content_id)

    # Meta
    @page_title = "Corrector"

    respond_to do |format|
      format.html # corrector/index.html.erb
    end
  end



  # Create new correction
  def create

    @mjson_correction = params[:correction].as_json
    
    # Parse correction to variables
    page_id = @mjson_correction['page']['id']
    issue_id = @mjson_correction['page']['issue_id']
    upload_directory = "#{ENV['AWS_S3_DIR_PAGE_CONTENTS']}/#{issue_id}"
    filename = "#{page_id}_correction.json"

    # Upload correction JSON file
    Storage.upload_data(filename, upload_directory, @mjson_correction.to_json)
    file_size = Storage.get_file_size(ENV['AWS_S3_DIR_PAGE_CONTENTS'], issue_id, filename)

    # Create entry in Database
    new_correction = PageContent.new
    new_correction.page_id = @mjson_correction['page']['id']
    new_correction.content_type = "correction"
    new_correction.filename = filename
    new_correction.user_id = current_user.id
    new_correction.file_size = file_size
    new_correction.save


    # upload mjson file
    # place entry in correction table
    # Page.reindex for elasticsearch
    # return success status

    respond_to do |format|
      format.js # corrector/new.html.erb ???
    end

  end



  # Profile
  def profile

    @user = User.find(current_user.id)

    # Meta
    @page_title = "Corrector - " + t('profile')

    respond_to do |format|
      format.html # corrector/profile.html.erb
    end
  end


  # Score
  def score

    @user = User.find(current_user.id)

    @total_pages = Page.of_scans_type.size
    @total_pages_to_correct = Page.of_scans_type.size
    @total_pages_corrected = Page.with_corrections.size
    @total_user_pages_corrected = PageContent.where(:content_type => 'correction').where(:user_id => current_user.id).size


    # Meta
    @page_title = "Corrector - " + t('score')

    respond_to do |format|
      format.html # corrector/score.html.erb
    end
  end



  # Help
  def help

    @user = User.find(current_user.id)

    # Meta
    @page_title = "Corrector - " + t('help')

    respond_to do |format|
      format.html # corrector/help.html.erb
    end
  end


  private

   # Geth the current information and output to a inline JS object in the returned page
   # This should be instead in a controller helper, as it is shared among several
   def current_page_information(publication_id, issue_id, page_id, page_content_id)
  
    if publication_id
      publication = Publication.find(publication_id)
      publication_name = publication.name
      publication_frequency = publication.frequency
    end
    
    if issue_id
      issue = Issue.find(issue_id)
      year = issue.date.year
      month = "%.2d" % issue.date.month.to_i
      day = issue.date.day
      #pages_widths_and_heights = issue.pages_widths_and_heights
      number_of_pages = issue.pages.size # get it from the pages_widths array, no need for another DB call

      unless publication_id
        publication_id = issue.publication_id
        publication = Publication.find(publication_id)
        publication_name = publication.name
        publication_frequency = publication.frequency
      end

    end

    # Pass the information to inline JS in this page
    gon.push({
      :publication => {
        :id => publication_id,
        :name => publication_name,
        :frequency => publication_frequency
      },
      :issue => {
        :id => issue_id,
        :date => {
          :year => year,
          :month => month,
          :day => day
        },
        :number_of_pages => number_of_pages,
        #:pages_widths_and_heights => pages_widths_and_heights,
        :page => page_id
      },
      :page_content_id => page_content_id
    })

  end

end

app/helpers/corrector_helper.rb
module CorrectorHelper
end

app/views/corrector/_navbar.html.erb
<!-- Fixed navbar -->
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand logo" href="<%= corrector_path %>"><%= image_tag('logo_marchiver.png', size: "34x34", :class => "pull-left")%></a>
      <a class="navbar-brand" href="<%= corrector_path %>">Marchiver</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
        <li class="<%= 'active' if current_page?(corrector_path) %>">
          <a href="<%= corrector_path %>">Corrector</a>
        </li>
        <li class="<%= 'active' if current_page?(corrector_help_path) %>">
          <a href="<%= corrector_help_path %>"><%= t('corrector.help') %></a>
        </li>
        <!--<li>
        <a href="<%= root_path %>"><%= t('corrector.archive') %></a>
        </li>-->
        <% if current_user.is_admin? %>
        <li>
          <a href="<%= admin_root_path %>"><%= t('corrector.admin') %></a>
        </li>
        <% end %>
        <li class="<%= 'active' if current_page?(user_profile_path) %>">
          <a href="<%= user_profile_path %>">
            <% if @user.image %>
              <%= image_tag(@user.image, size: "20") %>
            <% else %>
              <span class="glyphicon glyphicon-user" aria-hidden="true"></span>
            <% end %>
            <%= @user.name %></a>
        </li>
        <li>
          <a rel="nofollow" data-method="delete" href="/users/sign_out"><%= t('corrector.log-out') %></a>
        </li>
        <li class="dropdown" style="display: none;">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li class="dropdown-header">Nav header</li>
            <li><a href="#">Separated link</a></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>

app/views/corrector/help.html.erb
<%= render "navbar" %>

<div class="container corrector" id="help">
  
  <!-- help_header -->
  <div class="row">
    <div class="col-md-12" id="help_header">
      <h1><%= t('corrector.help') %></h1>
      <p style="text-align: center">Place here any help information to aid your users in the correction process.</p>
    </div>
  </div>

</div>

app/views/corrector/index.html.erb
<script type="text/javascript">


  
// On Document Ready
$(function() {

    // X-editable setup
    // turn to inline mode
    $.fn.editable.defaults.mode = 'inline' ;
    // Override loading gif to support Bootstrap and Rails asset compiling
    // $.fn.editableform.loading = '<div class="editableform-loading"></div>';
    $.fn.editableform.loading = '<div class="glyphicon glyphicon-repeat fast-right-spinner"></div>';
    // Buttons
    // $.fn.editableform.buttons = '<button type="submit" class="btn btn-primary btn-sm editable-submit"><i class="glyphicon glyphicon-ok"></i></button><button type="button" class="btn btn-default btn-sm editable-cancel"><i class="glyphicon glyphicon-remove"></i></button>'

    // Draw the issue
    get_issue(gon.issue.id);

    // Get the lines
    Corrector['mjson'] = <%= @mjson.html_safe %>

    // A little delay, as the map object
    // is still being created
    setTimeout(function(){
      bounds = Corrector.single_page_bounds;
      map.setMaxBounds(bounds);
      map.on('drag', function() {
        map.panInsideBounds(bounds, { animate: false });
      });
      map.options.minZoom = map.getZoom();

      $('.line').editable({
        clear: false,
        inputclass: 'line_inline_edit',
        emptytext: '&nbsp;',
        savenochange: true,
        unsavedclass: 'editable-unsaved',
        onblur: 'ignore'
      })
      // .on('shown', function(ev, editable) {
      //     setTimeout(function() {
      //         // sets cursor at beginning of line
      //         editable.input.$input.prop({ selectionStart: 0, selectionEnd:   0 });
      //         // .select() would select all the text
      //     },0);
      //});
      $('div.user_correction .line').fadeIn('fast');
    }, 1250);

    // Add to HTML the lines
    $.each(Corrector.mjson.areas, function( index, area ) {
       $.each(area.lines, function( index, line ) {
         $('div.user_correction').append('<div class="line" data-line-id=' + line.id + ' data-line-bbox=' + line.bbox.toString() + '><a href="#" data-type="textarea" data-pk="' + line.id + '">' + line.text + '</a></div>');
        //console.log(line.bbox.toString());
       });
       
    });

    // Number of lines
    Corrector['number_of_lines'] = $('div.user_correction .line').size();

    $('.info_total_lines').html(Corrector['number_of_lines']);

    // Updates the line info counter
    $('#editor_col').children().on('click', function (e) {
      setTimeout(function() {
        Corrector['number_of_corrected_lines'] = $('.line.editable-unsaved, .line.editable-empty').size();
        $('.info_corrected_lines').html(Corrector['number_of_corrected_lines']);
      },400)
    });

    // Fix for x-editable savenoshave trigger
    // it won't save if the clears the field and writes
    // everything or copy/pastes
    $(document).on('click', '.editable-submit', function() {
      line_id = $('.editable-open').data('line-id');
      setTimeout(function() {
        $(".line[data-line-id='" + line_id +"']").addClass('editable-unsaved');
      }, 200)
    });



    // Attach onClick event to each line
    $('div.user_correction .line').on('click', function() {

      line_id = $(this).data('line-id');
      
      // Find the line in the mJSON and get the line object 
      line = getObjects(Corrector.mjson.areas, 'id', line_id)[0];

      // x_left, y_left, x_right, y_right => Azure strucutre
      //page_lat_x = Corrector.page_x
      line_top_left = Viewer.rc.unproject([page_lat_px + parseInt(line.bbox[0]) , parseInt(line.bbox[1]) ]);
      line_bottom_right = Viewer.rc.unproject([page_lat_px + parseInt(line.bbox[2]) , parseInt(line.bbox[3]) ]);

      // set the line bounds
      var lineBounds = [
        line_top_left, // Top Left
        line_bottom_right // Bottom Right
      ];

      // Remove previous line selection, if that's the case
      if (Corrector.selected_line) {
        Corrector.selected_line.remove();
      }

      // Style of the line highlight on the page viewer
      var line_highlight_style = {
        color: "#fff12f",
        weight: 1,
        fillOpacity: 0.3,
      }

      // Draw rectangle and fit to bounds
      Corrector['selected_line'] = L.rectangle(lineBounds, line_highlight_style)
      Corrector.selected_line.addTo(map);
      map.fitBounds(lineBounds, {padding: [30, 30]});

    });


    // Make tooltips working
    $('[data-toggle="tooltip"]').tooltip();

    // On modal close, disable the spinner
    $('#submission_success, #submission_warning').on('hidden.bs.modal', function () {
      $('.btn-submit_text-corrections').find('i').removeClass('active');
    });

    // Submit text corrections functions
    $('.btn-submit_text-corrections').on('click', function() {
      
      // Toggle spinner
      $(this).find('i').toggleClass('active');

      // Verify that all lines are been checked
      if (Corrector['number_of_corrected_lines'] != Corrector['number_of_lines']) {
        lines_checked = false;
        $('#submission_warning').modal('show');
        return

      } else {
        lines_checked = true;
      }

      // Create correction JSON structure
      var corrections = {
        'lines': []
      }

      // Creates JSON itself
      $('.line.editable-unsaved').map(function() {
        lines = corrections['lines'];
        var line = new Object();
        line.id = $(this).data('line-id');
        line.bbox = $(this).data('line-bbox').split(",");
        line.text = $(this).text()
        lines.push(line)
      })

      // Clone original mjson and replace line values
      var mjson_correction = $.extend(true, {}, Corrector.mjson)
      $.each(mjson_correction.areas, function( index, area ) {
        $.each(area.lines, function( index, line ) {
            // Go through each submitted correct line
            $.each(corrections.lines, function(c_index, c_line) {
              // Replace line
              if (line.id == c_line.id) {
                line.text = c_line.text
              }
            });
        });
       
      });


      // Submit Correction
      $.ajax({
        url: '/corrector',
        dataType: 'json',
        contentType: 'application/json',
        type: 'POST',
        data: JSON.stringify({correction: mjson_correction}),
        success: function(data) {
          console.log("Successful");
        },
        failure: function(data) {
          console.log(data);
          alert("Unsuccessful");
        }
      });

      // Show modal
      $('#submission_success').modal('show');


    })

});



</script>


<%= render "navbar" %>



<div class="container corrector text_corrector">



  <div class="row">
    <div class="col-md-12" id="corrector_header">
      <h2 class="hide"><%= t('corrector.text_correction') %></h2>
      <h2 id="mobile_warning"><%= t('corrector.mobile_warning') %></h2>
    </div>

  </div>

  <div class="row">

    <div class="col-md-6" id="viewer_col">
        <div id="map_container">
          <div id="map">
          </div>
        </div>
    </div>

    <div class="col-md-6" id="editor_col">

      <div class="issue_info clearfix">
        <p class="pull-left"><%= l(@issue.date, format: "%B, %Y") %></p>
        <p class="pull-right"><%= t('corrector.page') %> <%= @page.number %></p>
      </div>

      <div class="text_correct">
        <!--<h3><%= t('corrector.text_correction') %></h3>-->
        <div class="inline_help clearfix">
          <p class="pull-left "><%= t('corrector.editor_help') %></p>
          <p class="pull-right"><a href="#" data-toggle="tooltip" data-placement="left" title="<%= t('corrector.editor_toggle_help') %>"><%= t('corrector.help') %></a></p>
        </div>

        <div class="user_correction">

        </div>

      </div>
      <div class="" style="display: none;">
        <p><%= t('corrector.question_missing_lines') %></p>
      </div>
      <div class="lines_info">
        <p><span class="info_corrected_lines">0</span> <%= t('corrector.of') %> <span class="info_total_lines"></span> <%= t('corrector.lines_checked') %></p>
      </div>

      <div class="form_send btn-group">
        <%= button_tag ('<i class="glyphicon glyphicon-refresh gly-spin"></i></span>' + t('corrector.submit_correction')).html_safe, class: "btn btn-primary btn-submit_text-corrections has-spinner" %>
      </div>
          
    <div>

    <!-- Modal for submissions -->
    <!-- Success -->
    <div id="submission_success" class="modal">
       <div class="modal-dialog modal-sm" role="document">
        <div class="modal-content">
          <div class="modal-header modal-header-success">
            <h5 class="modal-title"><%= t('corrector.success') %></h5>
          </div>
          <div class="modal-body">
            <p>
              <strong><span class="info_corrected_lines">0</span></strong> <%= t('corrector.lines_checked_and_fixed') %>.
            </p>
            <p>
              <%= t('corrector.thank_you') %> <%= current_user.first_name %>! 🙂
            </p>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-success" data-dismiss="modal2"><a href="/corrector"><%= t('corrector.correct_another_page') %></a></button>
          </div>
        </div>
      </div>
    </div>

    <!-- Lines Missing -->
    <div id="submission_warning" class="modal">
       <div class="modal-dialog modal-sm" role="document">
        <div class="modal-content">
          <div class="modal-header modal-header-warning">
            <h5 class="modal-title"><%= t('corrector.warning') %></h5>
          </div>
          <div class="modal-body">
            <p>
              <%= current_user.first_name ? current_user.first_name : current_user.name %>, <%= t('corrector.of_a_total') %> <strong><span class="info_total_lines"></span></strong> <%= t('corrector.lines_present') %> <strong><span class="info_corrected_lines">0</span></strong> <%= t('corrector.lines') %>. 😕
            </p>
            <p>
              <%= t('corrector.please_review') %>.<br>
              <%= t('corrector.thank_you') %>!
            </p>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal"><%= t('corrector.close') %></button>
          </div>
        </div>
      </div>
    </div>

</div>

app/views/corrector/profile.html.erb
<%= render "navbar" %>

<div class="container corrector" id="profile">
  
  <!-- profile_header -->
  <div class="row">
    <div class="col-md-12" id="profile_header">
      <h1><%= t('corrector.profile') %></h1>
      <p style="text-align: center;">Place her any account information regarding your users.</p>
    </div>
  </div>

</div>